Redis:
  Host: '0.0.0.0'
  DbId: 0
BackboneRedis:
  Host: '0.0.0.0'
  DbId: 0
UUIDCache:
  Backend: 'com.ddylan.xlib.uuid.impl.RedisUUIDCache'
NametagPacketRestriction:
  Enabled: false
  BypassPrefix: '&a'
Command:
  TimeThreshold: 10